# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Harsh Agrawal'
tagline:          "Beware! I'm looking over ya"
description:      'I am a 15 year old cool boy who loved reading dark & vicious <a href="http://thekidreader.wordpress.com" target="_blank">Books</a> and program <a href="https://github.com/Xavian-Brooker" target="_blank">AI</a> that can generate new pokemons.'
url:              https://drive.google.com/file/d/1wWDjR6NPzeImvfp81sBo_XFA9YDuio5n/view
baseurl:          /

author:
  name:           'Harsh Agrawal'
  url:            https://github.com/Xavian-Brooker

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
